version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=db
      - DB_DATABASE=mysql
      - DB_USERNAME=root
      - DB_PASSWORD=admin
    volumes:
      - .:/var/www/html
      - ./public:/var/www/html/public
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
