version: '3.8'
services:
    db:
        image: mysql:8.0
        container_name: laravel_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: mysql
            MYSQL_ROOT_PASSWORD: admin
        ports:
            -  "3306:3306"
